### PR TITLE
Add file source

### LINKED ISSUE #12: Add file source
Given the needs of non-cloud-based implementations, we need to be able to read files as a `flow.Source` (see #8).

### PR DESCRIPTION
**Pull request by andrewhare**
This adds a file source so that we can read files off disk as an input source (the CLI flag is `--input-file`).

This PR can also be used a as reference implementation for how to implement a new source.

Closes #12

### CODE REVIEW

**Comment by ztreinhart** [comment]
Maybe I'm missing something, but don't we need either an addition to the flow parser to allow this input source to be specified, or some code in `main` that watches for the command line flag and inserts the source into the input flow when the file flag is specified (à la `--prometheus-address`)?

**Comment by andrewhare** [comment]
@ztreinhart Good call, I forgot to add it to the default parser.

**Comment by andrewhare** [comment]
@ztreinhart: https://github.com/rename-this/vhs/pull/13/commits/d22f934715951d6df3417d140db573486368efde

**Review by ztreinhart — APPROVED** [review]
Looks good to me, and I like the idea of using this as an example source. It's nice and straightforward.

**Pull request merged**
